### ISSUE TITLE
Issue with running examples

### ISSUE THREAD

**Issue by bWanShiTong** [cbrnr/sleepecg#245]
When running `examples/classifiers/wrn_gru_mesa.py` I get following error, I have put my own nsrr token
```
Traceback (most recent call last):
  File "/home/wanshitong/.local/lib/python3.10/site-packages/sleepecg/io/nsrr.py", line 140, in _download_nsrr_file
    _download_file(url, target_filepath, checksum, "md5")
  File "/home/wanshitong/.local/lib/python3.10/site-packages/sleepecg/io/utils.py", line 90, in _download_file
    raise RuntimeError(
RuntimeError: Checksum mismatch for /home/wanshitong/.sleepecg/datasets/mesa/datasets/mesa-sleep-dataset-0.7.0.csv:
    'da42ac57ebd1f845000b996e824b046a' (expected)
    '576286f9f3cee1f16321135cf45aec01' (calculated)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/wanshitong/sleep-tests/test.py", line 30, in <module>
    records = list(read_mesa(offline=False))
  File "/home/wanshitong/.local/lib/python3.10/site-packages/sleepecg/io/sleep_readers.py", line 244, in read_mesa
    _download_nsrr_file(
  File "/home/wanshitong/.local/lib/python3.10/site-packages/sleepecg/io/nsrr.py", line 148, in _download_nsrr_file
    raise RuntimeError(f"Make sure you have access to {db_slug}!") from error
RuntimeError: Make sure you have access to mesa!
```

Downloaded file is `.html` and this is it content:

<details>

```html
<!DOCTYPE html>
<html lang='en'>

<head>
  <meta charset='utf-8'>
  <meta content='IE=Edge,chrome=1' http-equiv='X-UA-Compatible'>
  <meta content='width=device-width, initial-scale=1, shrink-to-fit=no' name='viewport'>
  <meta
    content='National Research Resource Resource offers free web access to large collections of de-identified physiological signals and clinical data elements collected in well-characterized research cohorts and clinical trials. The initial data resource is from the Sleep Heart Health Study.'
    name='description'>
  <meta content='Remo Mueller' name='author'>
  <meta content='sleep data, research datasets, study, sleep apnea, free access, download datasets' name='keywords'>

  <meta content='https://sleepdata.org/' property='og:url'>
  <meta content='Sleep Data - National Sleep Research Resource - NSRR' property='og:title'>
  <meta
    content='Offering free web access to large collections of de-identified physiological signals and clinical data elements in well-characterized research cohorts and clinical trials.'
    property='og:description'>
  <meta
    content='https://sleepdata.org/assets/nsrr_logo_256-2b7574fa87aea6bb9e2edd98af62b89528ea66a38a7f203460992b3cb94d34c8.png'
    property='og:image'>

  <meta content='Sleep Data - National Sleep Research Resource - NSRR' itemprop='name'>
  <meta
    content='Offering free web access to large collections of de-identified physiological signals and clinical data elements in well-characterized research cohorts and clinical trials.'
    itemprop='description'>
  <meta
    content='https://sleepdata.org/assets/nsrr_logo_256-2b7574fa87aea6bb9e2edd98af62b89528ea66a38a7f203460992b3cb94d34c8.png'
    itemprop='image'>

  <meta content='no-cache' name='turbolinks-cache-control'>
  <title>MESA Files - Sleep Data - National Sleep Research Resource - NSRR</title>
  <link rel="shortcut icon" type="image/x-icon"
    href="/assets/favicon-2aaa9a73588124fb9fe63e5e33de40d6804deaa9c049627e6328e2d090769ce1.ico" />
  <link rel="alternate" type="application/rss+xml" title="RSS" href="https://sleepdata.org/blog.atom" />
  <meta name="csrf-param" content="authenticity_token" />
  <meta name="csrf-token"
    content="aUwK2ZjZDKMLtf1z_aTVqp8cLjZjVOl7Oj33VjQHa_lRSDt3iYyS6_r2IlHTKzMXcyOYRh69i1gugpZSxqiOLg" />
  <script data-site='LOVVJMDS' defer src='https://fourteen-imagine.sleepdata.org/script.js'></script>

  <link rel="stylesheet" media="all"
    href="/assets/application-825633c2e05550ffe5d80cd29fce5e9557e9b99b9e366f0a095564949d6ee9a0.css"
    data-turbolinks-track="reload" />
  <script src="/assets/application-9d736f5b6294e9e72e67aee741123068db4dffa26b208a99360627da9191cf69.js"
    data-turbolinks-track="reload"></script>
  <script>
    //<![CDATA[
    var root_url = '/';
    //]]>
  </script>
</head>

<body class='full-page theme-bg theme-navy-bg' data-theme='navy' id='top'>

  <div class='bg-dark' id='service-announcement'>
    <div class='d-flex align-items-center container'>
      <div class='py-1 small text-white flex-fill'>
        <div class='text-center'>
          <i class="fas fa-info-circle"></i>
          We use cookies and other tools to enhance your experience on our website and to analyze our web traffic.
          <br>
          For more information about these cookies and the data collected, please refer to our
          <a data-object="service-announcement-link" data-cookie="privacy_policy_closed" href="/privacy-policy">Privacy
            Policy</a>.
        </div>
      </div>
      <a data-object="service-announcement" data-cookie="privacy_policy_closed" data-days="14"
        class="text-white no-underline" href="#"><i class="fas fa-times"></i></a>
    </div>
  </div>

  <div class='flash-bar'>
  </div>

  <div class='top-menu' id='top-menu'>
    <nav class='navbar navbar-expand-lg navbar-dark navbar-custom menu-navy'>
      <div class='container'>
        <a class="navbar-brand navbar-hide-scrolled" href="/">NSRR</a>
        <a data-object="scroll-anchor" class="navbar-brand navbar-show-scrolled" href="#top"><i
            class="fas fa-level-up-alt fa-flip-horizontal"></i>
          MESA Files
        </a>
        <button aria-controls='menu-body' aria-expanded='false' aria-label='Toggle navigation' class='navbar-toggler'
          data-target='#menu-body' data-toggle='collapse' type='button'>
          <span class='navbar-toggler-icon'></span>
        </button>
        <div class='menu-body collapse navbar-collapse' id='menu-body'>
          <ul class='navbar-nav mr-auto display-small-scrolled'>
            <li class='nav-item'>
              <a class="nav-link" href="/pages/about">About</a>
            </li>



            <li class='nav-item active'>
              <a class="nav-link" href="/datasets">Datasets</a>
            </li>

            <li class='nav-item'>
              <a class="nav-link" href="/tools">Tools</a>
            </li>

            <li class='nav-item'>
              <a class="nav-link" href="/forum">Forum</a>
            </li>

            <li class='nav-item'>
              <a class="nav-link" href="/blog">Blog</a>
            </li>

            <li class='nav-item'>
              <a class="nav-link" href="/share">Share data</a>
            </li>

            <li class='nav-item'>
              <a class="nav-link" href="/pages/webinars">Webinars</a>
            </li>


          </ul>
          <ul class='navbar-nav'>
            <li class='nav-item'>
              <a class="nav-link" href="/search"><i class="fas fa-search d-none d-lg-inline"></i>
                Search
              </a>
            </li>
            <li class='nav-item d-none d-lg-block'>
              <a class="nav-link notifications-link" href="/notifications"><i class="fas fa-bell"></i>
              </a>
            </li>
            <li class='nav-item dropdown d-none d-lg-block'>
              <div class='btn-group'>
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                  href="#"><img alt="" class="rounded img-ignore-selection"
                    src="/members/DasIsGoodUsername/profile_picture" width="20" height="20" />
                </a>
                <div class='dropdown-menu dropdown-menu-right dropdown-menu-custom'>
                  <div class='dropdown-menu-custom-inner'>
                    <a class="dropdown-item" href="/dashboard">My dashboard
                    </a><a class="dropdown-item" href="/members/DasIsGoodUsername/posts">My profile</a>
                    <a class="dropdown-item" href="/settings">Settings
                    </a>
                    <div class='dropdown-divider'></div>
                    <a class="dropdown-item" href="/sign_out">Sign out
                    </a>
                  </div>
                </div>
              </div>
            </li>
            <li class='nav-item'>
              <hr>
            </li>
            <li class='nav-item d-lg-none'>
              <a class="nav-link" href="/dashboard">My dashboard
              </a>
            </li>
            <li class='nav-item d-lg-none'>
              <a class="nav-link" href="/settings">Settings
              </a>
            </li>
            <li class='nav-item d-lg-none'>
              <a class="nav-link" href="/sign_out">Sign out
              </a>
            </li>

          </ul>

        </div>
      </div>
    </nav>
  </div>
  <div class='header-container'>
    <div class='container'>
      <h1 class='page-heading'>
        Multi-Ethnic Study of Atherosclerosis
      </h1>
    </div>
  </div>
  <!-- https://schema.org/ metadata for discovery -->
  <script type="application/ld+json">
{
  "@context": "https://schema.org/",
  "@type": "Dataset",
  "name": "Multi-Ethnic Study of Atherosclerosis",
  "description": "Multi-Ethnic Study of Atherosclerosis (MESA), is an NHLBI-sponsored 6-center collaborative longitudinal investigation of factors associated with the development of subclinical cardiovascular disease and the progression of subclinical to clinical cardiovascular disease in 6,814 black, white, Hispanic, and Chinese-American men and women initially ages 45-84 at baseline in 2000-2002. There have been four follow-up exams to date, in the years 2003-2004, 2004-2005, 2005-2007, and 2010-2011. Between 2010-2012, 2,237 participants also were enrolled in a Sleep Exam (MESA Sleep) which included full overnight unattended polysomnography, 7-day wrist-worn actigraphy, and a sleep questionnaire. The objectives of the sleep study are to understand how variations in sleep and sleep disorders vary across gender and ethnic groups and relate to measures of subclinical atherosclerosis.",
  "url": "https://sleepdata.org/datasets/mesa",
  "identifier": "https://doi.org/10.25822/n7hq-c406",
  "creator": [],
  "includedInDataCatalog": {
    "@type": "DataCatalog",
    "name": "sleepdata.org"
  }
}
</script>

  <div class='header-tabs'>
    <div class='container'>
      <div class='mb-0'>
        <a class="link-unstyled d-inline-block px-3 pt-2 pb-2 rounded-top header-tab " href="/datasets/mesa"><i
            class="fas fa-file-alt"></i>
          <div class='d-none d-sm-inline'>Docs</div>
        </a><a
          class="link-unstyled d-inline-block px-3 pt-2 pb-2 rounded-top header-tab border border-bottom-0 header-tab-active"
          href="/datasets/mesa/files"><i class="fas fa-file-medical-alt"></i>
          Files
        </a><a class="link-unstyled d-inline-block px-3 pt-2 pb-2 rounded-top header-tab "
          href="/datasets/mesa/variables"><i class="fas fa-chart-bar"></i>
          <div class='d-none d-sm-inline'>Variables</div>
        </a>
      </div>
    </div>
  </div>

  <div class='breadcrumb-container'>
    <div class='container'>
      <div id='breadcrumb'>
        <div class='d-none d-md-block float-right' style='margin-top: -3px !important;'>

          <div class='d-inline-block'>
            <ul class='pagination pagination-sm m-0'>
              <li class='page-item disabled'>
                <span class='page-link'>&laquo;</span>
              </li>
              <li class='page-item'>
                <span class='page-link text-dark'>
                  <strong>
                    1
                    to
                    7
                  </strong>
                  of
                  7
                </span>
              </li>
              <li class='page-item disabled'>
                <span class='page-link'>&raquo;</span>
              </li>
            </ul>
          </div>
        </div>
        <ol>
          <li><a href="/datasets/mesa">mesa</a></li>
          <li><a href="/datasets/mesa/files">files</a></li>
          <li>datasets</li>
        </ol>
      </div>

    </div>
  </div>
  <div class='py-3'>
    <div class='container'>
      <div id='folder'>
        <table class='table table-sm table-hover table-striped'>
          <col width='1px'>
          <tr class='tr-align-middle' id='dataset-file-76436-container'>
            <td>
              <i class="fas fa-folder-open"></i>
            </td>
            <td>
              <a data-object="" data-turbolinks="false" href="/datasets/mesa/files/datasets/archive">archive</a>
            </td>
            <td class='d-none d-md-table-cell'></td>
            <td class='d-none d-sm-table-cell text-right nowrap'>

            </td>

          </tr>
          <tr class='tr-align-middle' id='dataset-file-76437-container'>
            <td>
              <i class="far fa-file"></i>
            </td>
            <td>
              <a data-object="" data-turbolinks="false"
                href="/datasets/mesa/files/m/browser/datasets/CHANGELOG.md?preview=1">CHANGELOG.md</a>
            </td>
            <td class='d-none d-md-table-cell'>2024-02-21 10:50:58</td>
            <td class='d-none d-sm-table-cell text-right nowrap'>
              2.24 KB
              <i class="fas fa-globe-americas"></i>
            </td>

          </tr>
          <tr class='tr-align-middle' id='dataset-file-232123-container'>
            <td>
              <i class="far fa-file"></i>
            </td>
            <td>
              <a data-object="" data-turbolinks="false"
                href="/datasets/mesa/files/m/browser/datasets/mesa-data-dictionary-0.7.0-domains.csv">mesa-data-dictionary-0.7.0-domains.csv</a>
            </td>
            <td class='d-none d-md-table-cell'>2024-02-21 10:50:57</td>
            <td class='d-none d-sm-table-cell text-right nowrap'>
              5.38 KB
              <i class="fas fa-globe-americas"></i>
            </td>

          </tr>
          <tr class='tr-align-middle' id='dataset-file-232124-container'>
            <td>
              <i class="far fa-file"></i>
            </td>
            <td>
              <a data-object="" data-turbolinks="false"
                href="/datasets/mesa/files/m/browser/datasets/mesa-data-dictionary-0.7.0-forms.csv">mesa-data-dictionary-0.7.0-forms.csv</a>
            </td>
            <td class='d-none d-md-table-cell'>2024-02-21 10:50:57</td>
            <td class='d-none d-sm-table-cell text-right nowrap'>
              179 Bytes
              <i class="fas fa-globe-americas"></i>
            </td>

          </tr>
          <tr class='tr-align-middle' id='dataset-file-232125-container'>
            <td>
              <i class="far fa-file"></i>
            </td>
            <td>
              <a data-object="" data-turbolinks="false"
                href="/datasets/mesa/files/m/browser/datasets/mesa-data-dictionary-0.7.0-variables.csv">mesa-data-dictionary-0.7.0-variables.csv</a>
            </td>
            <td class='d-none d-md-table-cell'>2024-02-21 10:50:58</td>
            <td class='d-none d-sm-table-cell text-right nowrap'>
              182 KB
              <i class="fas fa-globe-americas"></i>
            </td>

          </tr>
          <tr class='tr-align-middle' id='dataset-file-232126-container'>
            <td>
              <i class="far fa-file"></i>
            </td>
            <td>
              mesa-sleep-dataset-0.7.0.csv
            </td>
            <td class='d-none d-md-table-cell'>2024-02-21 10:50:54</td>
            <td class='d-none d-sm-table-cell text-right nowrap'>
              7.27 MB
            </td>

          </tr>
          <tr class='tr-align-middle' id='dataset-file-232127-container'>
            <td>
              <i class="far fa-file"></i>
            </td>
            <td>
              mesa-sleep-harmonized-dataset-0.7.0.csv
            </td>
            <td class='d-none d-md-table-cell'>2024-02-21 10:50:56</td>
            <td class='d-none d-sm-table-cell text-right nowrap'>
              347 KB
            </td>

          </tr>
        </table>
        <div class='code-container'>
          <span class='code-command-blank'>
            <a data-object="suppress-click" data-clipboard-text="nsrr download mesa/datasets" data-placement="bottom"
              data-container="body" data-title="Copied!" data-trigger="manual" style="text-decoration: none" href="#"><i
                class="fas fa-paste"></i>
            </a>nsrr download
            mesa/datasets
          </span>
        </div>
        <div class='card mx-auto text-center' style='max-width: 30rem;'>
          <h4 class='card-header'>
            Don't have the NSRR gem?
          </h4>
          <div class='card-body'>
            Install using our
            <a href="https://github.com/nsrr/nsrr-gem/blob/master/README.md#prerequisites">NSRR Gem Installation
              Instructions</a>.
          </div>
        </div>

      </div>
    </div>
  </div>

  <div class='footer-container theme-navy-bg'>
    <div class='container'>
      <div class='footer'>
        <div class='nowrap row'>
          <div class='col'>
            &copy;
            2024
            <div class='d-inline d-md-none'><a href="/about">NSRR</a></div>
            <div class='d-none d-md-inline'><a href="/about">National Sleep Research Resource</a></div>
          </div>
          <div class='col text-center d-none d-sm-block'>
            <small class='px-2'><a href="/privacy-policy">Privacy</a></small>
          </div>
          <div class='col text-right'>
            <a href="/contact">Contact Us</a>
            |
            <a href="/about">Funded By NHLBI</a>
          </div>
        </div>
      </div>
    </div>
  </div>

</body>

</html>
```
</details>

**Comment by cbrnr** [comment]
I just tried it on my computer and it works. Are you sure you pasted the correct access token? You can view your token at https://sleepdata.org/token.

Also, the token needs to grant access to MESA, you can check if that's the case at https://sleepdata.org/data/requests; it should list "mesa" at the bottom.

**Comment by bWanShiTong** [comment]
I don't have access to MESA, how can I get it?

**Comment by cbrnr** [comment]
As mentioned [here](https://sleepecg.readthedocs.io/en/stable/datasets/), you need to submit a data access request. If they grant it, you will get a token, which you can use in SleepECG.
